/**
 * Reusable/portable screening report — the "pay once, reuse across every Rentra
 * listing" engine (CA-first monetization model).
 *
 * Compliance shape (see the ScreeningReport model in schema.prisma):
 *  - The report is generated by a REGISTERED consumer reporting agency
 *    (Plaid Check for income/cash-flow; TransUnion SmartMove for
 *    credit/criminal/eviction). The CRA is the agent of record and carries the
 *    FCRA + CA ICRAA duties; Rentra resells and the landlord is the FCRA
 *    "end user". Do NOT score raw non-Check Plaid data into a landlord-facing
 *    result here — that both breaks Plaid's ToS and makes Rentra an
 *    unregistered CRA.
 *  - A report is reusable for REUSE_WINDOW_DAYS (CA AB 2559 freshness = 30d).
 *  - Consent + the exact disclosure shown are captured BEFORE the pull (ICRAA).
 */

// CA AB 2559 uses a 30-day freshness standard for reusable screening reports.
export const REUSE_WINDOW_DAYS = 30

/**
 * The "pay once, reuse everywhere" gate. Returns this user's still-valid
 * screening report, or null. When one exists we link it to the new application
 * instead of charging again (CA AB 2559 bars a second fee for an in-network
 * report). `userId` may be a tenant or a cosigner.
 *
 * @param {import('@prisma/client').PrismaClient} prisma
 * @param {string} userId
 */
export async function findReusableReport(prisma, userId) {
  return prisma.screeningReport.findFirst({
    where: {
      userId,
      status: 'complete',
      expiresAt: { gt: new Date() },
    },
    orderBy: { issuedAt: 'desc' },
  })
}

/**
 * Reuse an unexpired report if one exists, otherwise generate a fresh one via
 * the CRA. Callers must have captured consent first and pass it through.
 *
 * @param {import('@prisma/client').PrismaClient} prisma
 * @param {object} opts
 * @param {string} opts.userId
 * @param {'plaid_check'|'transunion'|'checkr'} opts.provider
 * @param {Date}   opts.consentAt          consent captured before the pull (ICRAA)
 * @param {string} opts.disclosureVersion  the exact disclosure the user agreed to
 * @returns {Promise<object>} the reusable ScreeningReport row
 */
export async function createOrReuseScreeningReport(prisma, opts) {
  const existing = await findReusableReport(prisma, opts.userId)
  if (existing) return existing

  // --- CRA INTEGRATION POINT ------------------------------------------------
  // Wire a real consumer reporting agency here before generating live reports:
  //   Plaid Check → Consumer Report API (income / cash-flow)
  //   TransUnion  → SmartMove tenant-initiated soft pull (credit/criminal/eviction)
  // The call should return: externalReportId, verifiedMonthlyIncome,
  // creditScore/creditTier, backgroundResult, incomeSource, and reportUrl (the
  // applicant's free copy, required by CA ICRAA). Then persist and return:
  //
  //   const cra = await plaidCheck.createConsumerReport({ userId: opts.userId })
  //   const issuedAt = new Date()
  //   const expiresAt = new Date(issuedAt.getTime() + REUSE_WINDOW_DAYS * 86400000)
  //   return prisma.screeningReport.create({ data: {
  //     userId: opts.userId, provider: opts.provider,
  //     externalReportId: cra.id, status: 'complete',
  //     verifiedMonthlyIncome: cra.monthlyIncome, incomeSource: cra.incomeSource,
  //     creditScore: cra.creditScore, creditTier: cra.creditTier,
  //     backgroundResult: cra.background, reportUrl: cra.reportUrl,
  //     issuedAt, expiresAt,
  //     consentAt: opts.consentAt, disclosureVersion: opts.disclosureVersion,
  //   }})
  //
  // Fail loudly rather than silently fabricating a "complete" report — a fake
  // screening result is exactly the integrity problem this model replaces.
  throw new Error(
    'CRA integration not configured: wire Plaid Check / TransUnion before generating live screening reports'
  )
}
